apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: angry-asp-python 
  janus-idp.io/tekton: angry-asp-python
  backstage.io/kubernetes-id: angry-asp-python
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: angry-asp-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  