apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: angry-asp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: angry-asp-python 
  name: angry-asp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: angry-asp-python 
